#language: cpp
#
#before_install:
#  - sudo add-apt-repository ppa:beineri/opt-qt541 -y
#install:
#    - sudo apt-get install qt54base qt54websockets
#
#script:
#- source /opt/qt54/bin/qt54-env.sh
#  - qmake -qt=qt5 -v
#  - qmake -qt=qt5
#  - make
#  - make -k check

language: cpp

matrix:
 include:
  - os: linux
    dist: trusty
    sudo: required
    compiler: gcc
    env:
     - QT_BASE=56
  - os: osx
    compiler: clang
    env:
     - QT_BASE=56

before_install:
  - if [[ "$QT_BASE" = "56" && "$TRAVIS_OS_NAME" = "linux" ]]; then sudo add-apt-repository ppa:beineri/opt-qt561-trusty -y; fi
  - if [ "$TRAVIS_OS_NAME" = "linux" ]; then
      sudo apt-get update -qq;
    else
      brew update;
    fi

install:
  - if [ "$QT_BASE" = "56" ]; then
      if [ "$TRAVIS_OS_NAME" = "linux" ]; then
        sudo apt-get install -qq qt56base; source /opt/qt56/bin/qt56-env.sh;
      else
        brew install qt5;
        brew link --force qt5;
      fi
    fi

script:
  - qmake -v
  - qmake -r samples/TwoLeggedTokenUtility/
  - make
  - make clean
  - qmake -r samples/BucketExplorer/
  - make
  - make clean
  - qmake -r samples/ModelConverter/
  - make
  - make clean
  - qmake -r tests/md_tests/ModelDerivativeTestSuite
  - make


notifications:
  email: false
